#!/usr/bin/env python3
import argparse
import json
import os
from pathlib import Path
from cryptography.hazmat.primitives import hashes, hmac
from cryptography.hazmat.backends import default_backend
import base64

def gen_secrets(channels: list[int]) -> bytes:
    """
    Genera un archivo de secretos seguro con claves específicas para canales y clave MAC.
    
    :param channels: Lista de números de canal que serán válidos en esta implementación.
    :returns: Contenido del archivo de secretos en formato JSON (bytes).
    """
    # Genera la master key (32 bytes para AES-256)
    master_key = os.urandom(32)
    
    # Deriva las claves específicas de cada canal usando HMAC-SHA256
    channel_keys = {}
    for channel in channels:
        h_obj = hmac.HMAC(master_key, hashes.SHA256(), backend=default_backend())
        h_obj.update(f"channel_{channel}".encode())
        channel_keys[channel] = h_obj.finalize()
    
    # Deriva la clave MAC
    h_obj = hmac.HMAC(master_key, hashes.SHA256(), backend=default_backend())
    h_obj.update(b"mac_key")
    mac_key = h_obj.finalize()
    
    # Crea el diccionario de secretos
    secrets = {
        "master_key": base64.b64encode(master_key).decode(),
        "channels": channels,
        "channel_keys": {
            str(ch): base64.b64encode(key).decode() for ch, key in channel_keys.items()
        },
        "mac_key": base64.b64encode(mac_key).decode()
    }
    
    return json.dumps(secrets).encode()

def write_secrets_header(secrets: dict, header_path: Path):
    """
    Genera un archivo header en C con los secretos.
    Se crean definiciones para MASTER_KEY_BASE64, MAC_KEY_BASE64 y CHANNEL_KEY_1 hasta CHANNEL_KEY_8.
    Si algún canal no existe en los secretos, se define una clave dummy (32 bytes en cero, codificada en Base64).
    """
    def dummy_key():
        return base64.b64encode(b'\x00' * 32).decode()
    
    lines = []
    lines.append("/* Autogenerated header from gen_secrets.py */")
    lines.append("#ifndef SECRETS_H")
    lines.append("#define SECRETS_H")
    lines.append("")
    lines.append('static const char MASTER_KEY_BASE64[] = "{}";'.format(secrets.get("master_key", "")))
    lines.append("")
    lines.append('static const char MAC_KEY_BASE64[] = "{}";'.format(secrets.get("mac_key", "")))
    lines.append("")
    # Se esperan definiciones para 8 claves de canal (canales 1 a 8)
    for ch in range(1, 9):
        key = secrets.get("channel_keys", {}).get(str(ch), dummy_key())
        lines.append('static const char CHANNEL_KEY_{}[] = "{}";'.format(ch, key))
    lines.append("")
    lines.append("#endif // SECRETS_H")
    
    with open(header_path, "w") as f:
        f.write("\n".join(lines))

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", "-f", action="store_true",
                        help="Forzar creación del archivo de secretos, sobrescribiendo el existente")
    parser.add_argument("--header", type=Path,
                        help="Ruta para el archivo header de salida (opcional)")
    parser.add_argument("secrets_file", type=Path,
                        help="Ruta al archivo de secretos a crear")
    parser.add_argument("channels", nargs="+", type=int,
                        help="Canales soportados. Nota: el canal 0 (broadcast) se considera siempre válido")
    return parser.parse_args()

def main():
    args = parse_args()
    secrets_bytes = gen_secrets(args.channels)
    secrets = json.loads(secrets_bytes.decode())
    
    # Escribe el archivo JSON de secretos
    with open(args.secrets_file, "wb" if args.force else "xb") as f:
        f.write(secrets_bytes)
    print(f"Se escribió el archivo de secretos en {str(args.secrets_file.absolute())}")
    
    # Si se solicita un header, se genera
    if args.header:
        write_secrets_header(secrets, args.header)
        print(f"Se escribió el header en {str(args.header.absolute())}")

if __name__ == "__main__":
    main()
